# PH Regional Disparities in Agricultural Wages and Household Income Analysis

## LOADING DATA

In [2]:
import pandas as pd
df = pd.read_excel(r"C:\Users\User\Downloads\Consolidated_Poverty_data\consolidated_philippines_poverty_data.xlsx")
df.head()

,regDesc,agr_wage_farm_workers_allgender_2015,agr_wage_farm_workers_male_2015,agr_wage_farm_workers_female_2015,avg_annual_total_incm_farm_households_02_03,avg_annual_farm_incm_farm_households_02_03,avg_annual_off_farm_incm_farm_households_02_03,avg_annual_non_farm_incm_farm_households_02_03,avg_annual_other_sources_incm_farm_households_02_03,avg_rural_income_2000,total_emply_2016
0,Armm,162.89,163.65,103.81,73356,34026,5737,24936,8657,73673.0,1140
1,Bicol Region,167.99,169.95,119.52,82988,36579,7348,30381,8680,72626.0,2331
2,Cagayan Valley,228.77,232.64,199.98,145809,87353,6909,39894,11653,94212.0,1482
3,Calabarzon,230.92,231.45,172.04,143075,64498,8444,48590,21543,NaN,5687
4,Car,206.68,211.04,195.62,127067,71142,9731,37178,9016,95635.0,765

## Checking Data Structure

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 11 columns):
 #   Column                                               Non-Null Count  Dtype
---  ------                                               --------------  -----
 0   regDesc                                              16 non-null     object
 1   agr_wage_farm_workers_allgender_2015                 16 non-null     float64
 2   agr_wage_farm_workers_male_2015                      16 non-null     float64
 3   agr_wage_farm_workers_female_2015                    16 non-null     float64
 4   avg_annual_total_incm_farm_households_02_03          16 non-null     int64
 5   avg_annual_farm_incm_farm_households_02_03           16 non-null     int64
 6   avg_annual_off_farm_incm_farm_households_02_03       16 non-null     int64
 7   avg_annual_non_farm_incm_farm_households_02_03       16 non-null     int64
 8   avg_annual_other_sources_incm_farm_households_02_03  16 non-null     int64
 9   avg_rural_income_2000                                14 non-null     float64
 10  total_emply_2016                                     16 non-null     int64
dtypes: float64(4), int64(6), object(1)
memory usage: 1.5+ KB

## Checking & filling missing values

In [5]:
median_value = df['avg_rural_income_2000'].median()
df['avg_rural_income_2000'].fillna(median_value)

df.isnull().sum()

regDesc                                                0
agr_wage_farm_workers_allgender_2015                   0
agr_wage_farm_workers_male_2015                        0
agr_wage_farm_workers_female_2015                      0
avg_annual_total_incm_farm_households_02_03            0
avg_annual_farm_incm_farm_households_02_03             0
avg_annual_off_farm_incm_farm_households_02_03         0
avg_annual_non_farm_incm_farm_households_02_03         0
avg_annual_other_sources_incm_farm_households_02_03    0
avg_rural_income_2000                                  0
total_emply_2016                                       0
dtype: int64

## Summary Statistics

In [6]:
df.describe(include="all")

,regDesc,agr_wage_farm_workers_allgender_2015,agr_wage_farm_workers_male_2015,agr_wage_farm_workers_female_2015,avg_annual_total_incm_farm_households_02_03,avg_annual_farm_incm_farm_households_02_03,avg_annual_off_farm_incm_farm_households_02_03,avg_annual_non_farm_incm_farm_households_02_03,avg_annual_other_sources_incm_farm_households_02_03,avg_rural_income_2000,total_emply_2016
count,16,16.000000,16.000000,16.000000,16.000000,16.000000,16.000000,16.000000,16.000000,16.00000,16.000000
unique,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,Armm,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,187.784375,189.839375,162.208125,107012.625000,58346.562500,6864.062500,31323.750000,10478.250000,80106.37500,2233.750000
std,NaN,34.052310,34.086908,31.250705,28907.450663,18920.636219,1915.653116,10214.735412,6118.979822,16635.40149,1306.409201
min,NaN,156.170000,158.550000,103.810000,72177.000000,28074.000000,4256.000000,13892.000000,4776.000000,63574.00000,765.000000
25%,NaN,161.947500,162.900000,151.210000,82452.000000,45835.750000,5701.000000,23678.750000,6756.250000,71581.25000,1424.500000
50%,NaN,168.335000,169.890000,159.025000,100500.000000,54069.500000,6326.000000,32243.000000,8845.500000,73819.50000,1921.000000
75%,NaN,212.202500,216.142500,189.740000,128901.750000,72032.000000,7622.000000,36335.000000,10537.000000,83540.25000,2550.250000
max,NaN,257.970000,259.040000,204.730000,158130.000000,87353.000000,11118.000000,50413.000000,26681.000000,125626.00000,5687.000000

## Feature Engineering

### Creating farm_income_share

In [7]:
df['farm_income_share'] = df['avg_annual_farm_incm_farm_households_02_03']/df['avg_annual_total_incm_farm_households_02_03']
df['farm_income_share'].head(16)

0     0.463848
1     0.440775
2     0.599092
3     0.450799
4     0.559878
5     0.638579
6     0.537836
7     0.388960
8     0.683525
9     0.574028
10    0.434468
11    0.591760
12    0.607395
13    0.627435
14    0.516154
15    0.545018
Name: farm_income_share, dtype: float64

### Creating off-farm_income_share

In [8]:
df['off_farm_income_share'] = df['avg_annual_off_farm_incm_farm_households_02_03']/df['avg_annual_total_incm_farm_households_02_03']
df['off_farm_income_share'].head(16)

0     0.078208
1     0.088543
2     0.047384
3     0.059018
4     0.076582
5     0.131467
6     0.038405
7     0.077227
8     0.055010
9     0.073525
10    0.036734
11    0.052116
12    0.051714
13    0.069543
14    0.084379
15    0.059863
Name: off_farm_income_share, dtype: float64

### Creating non-farm_income_share

In [9]:
df['non_farm_income_share'] = df['avg_annual_non_farm_incm_farm_households_02_03']/df['avg_annual_total_incm_farm_households_02_03']
df['non_farm_income_share'].head(16)

0     0.339931
1     0.366089
2     0.273605
3     0.339612
4     0.292586
5     0.164268
6     0.318807
7     0.430262
8     0.172838
9     0.288620
10    0.303902
11    0.279332
12    0.282859
13    0.250420
14    0.272324
15    0.336575
Name: non_farm_income_share, dtype: float64

### Creating other_sources_income_share

In [13]:
df['other_sources_income_share'] = df['avg_annual_other_sources_incm_farm_households_02_03']/df['avg_annual_total_incm_farm_households_02_03']
df['other_sources_income_share'].head(16)

0     0.118014
1     0.104593
2     0.079920
3     0.150571
4     0.070955
5     0.065686
6     0.104952
7     0.103551
8     0.088627
9     0.063828
10    0.224896
11    0.076792
12    0.058032
13    0.052602
14    0.127144
15    0.058544
Name: other_sources_income_share, dtype: float64

## DATA INTEGRATION

In [33]:
# Integrate connection
import mysql.connector

In [35]:
db = mysql.connector.connect (
   host = "localhost",
   user = "root",
   password = "password123",
    database= "project1"
)

mycursor= db.cursor()
print(db)

<mysql.connector.connection_cext.CMySQLConnection object at 0x00000205AE8DB050>

In [36]:
from sqlalchemy import create_engine

engine = create_engine("mysql+pymysql://root:password123@localhost/project1")

In [37]:
df.to_sql("my_table", con=engine, if_exists="replace", index=False)

16